### ISSUE TITLE
System Architecture Analysis Lanjutan

### ISSUE THREAD

**Issue by rizki-tri-prasetio** [MKOM-BSI-2013/Scriptseeker#13]
Pak Syarif.. Ini Tinggal diberikan komentar lalu di close aja ya issue nya..
Formalitas doang.. hehehe

**Comment by syarifsfq** [comment]
set and ready!!!

**Comment by erna-irawan** [comment]
file-file yang harus di upload ada di pak Toni ya..
Saya labelin di issue untuk pak syarif untuk implementasi file project dan file index.
